// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicOperations: typeof import('./components/home/left-sidebar/BasicOperations.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FileDirectories: typeof import('./components/home/left-sidebar/FileDirectories.vue')['default']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpDiscount: typeof import('~icons/ep/discount')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpIcon: typeof import('~icons/ep/icon')['default']
    IEpIconMenu: typeof import('~icons/ep/icon-menu')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    LeftOptionBar: typeof import('./components/home/left-sidebar/LeftOptionBar.vue')['default']
    PersonCard: typeof import('./components/home/left-sidebar/dialog/PersonCard.vue')['default']
    PersonOperationsDialog: typeof import('./components/home/left-sidebar/dialog/PersonOperationsDialog.vue')['default']
    Tags: typeof import('./components/home/left-sidebar/Tags.vue')['default']
  }
}
